# fits in 46gb

defaults:
  - umi_policy_base
  - model: diffusion_unet_timm

dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: True
  drop_last: True

val_dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: True
  drop_last: True

optimizer:
  lr: 7.5e-5
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  seed: 42
  debug: False
  resume: False
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 2000
  num_epochs: 120
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  freeze_encoder: False
  # training loop control
  # in epochs
  visualize_every: 10
  val_every: 1
  sample_every: 5
  sample_min_size: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0
  mixed_precision: 'no'
  log_grad_norm_every: 50
  clip_grad_norm: null