session_dir: ''
overwrite: false
task_names: [] # Extract these tasks from each demo for addition to the replay buffer
stages:
  - dataset_plan
  - replay_buffer

rotate_head: false
verbose: true

replay_buffer:
  vis_rgb: false
  vis_video: false
  num_workers: 16
  episode_keep_ratio: 1.0 # Keep only the first portion of each episode (0-1]
  episode_keep_ratio_name_filter: 
    - "2026-01-18" # Apply keep ratio only when episode name contains this string or any in list
  save_pointmap: true
  save_pointmap_side: 'head'
  save_depth: false
  iphone_calibration: 'calibration/iphone15pro_capture_calibration.yaml'
  out_res_rgb: 224
  out_res_pointmap: 512
  save_look_at_point: true

# don't log hydra job
defaults:
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
