_target_: hommi.train_network.policy.diffusion_transformer_timm_policy.DiffusionTransformerTimmPolicy
name: diffusion_transformer_timm

shape_meta: ${shape_meta}

n_emb: 768

noise_scheduler:
  _target_: diffusers.DDIMScheduler
  num_train_timesteps: 50
  beta_start: 0.0001
  beta_end: 0.02
  # beta_schedule is important
  # this is the best we found
  beta_schedule: squaredcos_cap_v2
  clip_sample: True
  set_alpha_to_one: True
  steps_offset: 0
  prediction_type: epsilon # or sample

obs_encoder:
  _target_: hommi.train_network.model.vision.transformer_obs_encoder.TransformerObsEncoder
  shape_meta: ${shape_meta}
  global_pool: ''
  n_emb: ${..n_emb}

  ##### from scratch #####
  # model_name: 'vit_base_patch16_224'
  # model_name: 'resnet34'
  # model_name: 'vit_tiny_patch16_224'
  # model_name: 'efficientnet_b0'
  # model_name: 'efficientnet_b3'
  # pretrained: False
  # frozen: False

  ##### from scratch #####
  # model_name: 'resnet34.a1_in1k'
  model_name: 'vit_base_patch16_clip_224.openai'
  # model_name: 'vit_small_patch14_reg4_dinov2.lvd142m'  # 518*518 images
  # model_name: 'vit_small_patch8_224.dino'
  # model_name: 'convnext_base.clip_laion2b_augreg_ft_in12k'
  pretrained: True
  frozen: False

  # 'cls' or 'avg' or 'max' or 'soft_attention' or 'spatial_embedding' or 'transformer' or 'attention_pool_2d'
  feature_aggregation: 'cls'

  # it only works for resnet. 32 (7x7) or 16 (14x14)
  downsample_ratio: 32

  train_image_transforms: ${...task.train_image_transforms}
  eval_image_transforms: ${...task.eval_image_transforms}

  use_group_norm: True
  share_rgb_model: False
  use_vision_norm: True
  concat_low_dims: True

num_inference_steps: 16
input_pertub: 0.1 # reference: https://github.com/forever208/DDPM-IP
n_layer: 7
n_head: 8
p_drop_attn: 0.1
