_target_: hommi.train_network.policy.diffusion_dit_image_policy.DiffusionDiTImagePolicy
name: diffusion_dit

shape_meta: ${shape_meta}

noise_scheduler:
  _target_: diffusers.DDIMScheduler
  num_train_timesteps: 100
  beta_start: 0.0001
  beta_end: 0.02
  # beta_schedule is important
  # this is the best we found
  beta_schedule: squaredcos_cap_v2
  clip_sample: True
  set_alpha_to_one: True
  steps_offset: 0
  prediction_type: epsilon # or sample

obs_encoder:
  _target_: hommi.train_network.model.vision_3d.dit_obs3d_encoder.DiTObs3DEncoder
  shape_meta: ${shape_meta}
  global_pool: ''

  ##### from scratch #####
  # model_name: 'vit_base_patch16_224'
  # model_name: 'resnet34'
  # model_name: 'vit_tiny_patch16_224'
  # model_name: 'efficientnet_b0'
  # model_name: 'efficientnet_b3'
  # pretrained: False
  # frozen: False

  ##### from scratch #####
  # model_name: 'resnet34.a1_in1k'
  # model_name: 'vit_base_patch16_clip_224.openai'
  # model_name: 'dinov3-vits16-pretrain-lvd1689m'
  model_name: 'dinov3-vitb16-pretrain-lvd1689m'
  # model_name: 'vit_small_patch14_reg4_dinov2.lvd142m'  # 518*518 images
  # model_name: 'vit_small_patch8_224.dino'
  # model_name: 'convnext_base.clip_laion2b_augreg_ft_in12k'
  pretrained: True
  frozen: False

  # 'cls' or 'avg' or 'max' or 'soft_attention' or 'spatial_embedding' or 'transformer' or 'attention_pool_2d' or 'patch'
  feature_aggregation: 'cls'

  # it only works for resnet. 32 (7x7) or 16 (14x14)
  downsample_ratio: 32

  train_image_transforms: ${...task.train_image_transforms}
  eval_image_transforms: ${...task.eval_image_transforms}

  use_group_norm: True
  share_rgb_model: True
  use_vision_norm: True

  # pointcloud_model_name: 'vit_base_patch14_dinov2.lvd142m'
  # pointcloud_model_name: 'dinov3-vits16-pretrain-lvd1689m'
  pointcloud_model_name: 'dinov3-vitb16-pretrain-lvd1689m'
  freeze_pointcloud_model: False
  share_pointcloud_model: True
  position_embedding_dim: 60
  xyz_proj_type: 'nerf'
  num_points: 512
  downsample_mode: 'feat'
  # do_crop: False
  # egocentric_frame: True
  visualize_attention: False
  debug_nan_checks: False
  add_pos_emb: False
  wrist_pos_emb: False

  # pointcloud_augmentation:
  #   _target_: hommi.train_network.model.vision_3d.pointcloud_augmentation.PointCloud3DAugmentation
  #   augmentation_prob: 0.5
  #   translation_range: [-0.05, 0.05]
  #   scaling_range: [0.95, 1.05]
  #   jitter_std: 0.01
  #   dropout_ratio: [0.0, 0.1]
  #   preserve_hand_regions: False

  head_wrist_attention: 'none'
  n_emb: 768
  wrist_mask_prob: 0.0

horizon: ${..task.action_horizon}
n_action_steps: 8
n_obs_steps: ${..task.img_obs_horizon} # 2
num_inference_steps: 16
obs_as_global_cond: True

# Diffusion Transformer Architecture hyperparams
attention_embed_dim: 768
diffusion_timestep_embed_dim: 256
depth: 10
num_heads: 12
mlp_ratio: 4.00
qkv_bias: True
use_rms_norm: True
input_perturbation: 0.1
train_diffusion_n_samples: 8
